name: Terraform Pipeline

on:
  push:
    branches:
      - infastrucutre
  pull_request:
    branches:
      - infastrucutre

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: infra/.terraform

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/.terraform

      # Step 6: Terraform Apply (requires approval for PRs)
      #- name: Terraform Apply
      #  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #  run: terraform apply -auto-approve
      #  working-directory: ./terraform
